name: daily_app
description: 감정 일기 앱

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter:
  assets:
    - assets/emotions/
    - assets/weather/
    - assets/solution/

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  table_calendar: ^3.0.9
  intl: ^0.20.2
  fl_chart: ^0.70.2
  flutter_screenutil: ^5.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
